package com.akarsh.auth.repository;

import com.akarsh.auth.entity.User;
import com.akarsh.auth.entity.Vendor;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;


@Repository
public interface VendorRepository extends JpaRepository<Vendor, Long> {
    Vendor findByCreatedBy(User createdBy);
    boolean existsByCreatedBy(User createdBy);
    Vendor findByEmail(String email);
    
    // Updated method that works with GENERATED BY DEFAULT AS IDENTITY
    @Query(value = "INSERT INTO vendors (id, name, email, phone, created_by, created_at) VALUES (:id, :#{#vendor.name}, :#{#vendor.email}, :#{#vendor.phone}, :#{#vendor.createdBy.id}, CURRENT_TIMESTAMP)", nativeQuery = true)
    @Modifying
    void saveWithId(@Param("vendor") Vendor vendor, @Param("id") Long id);

}


